server:
  port: 9001
  servlet:
    context-path: /

spring:
  application:
    name: offcn_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health?serverTimezone=Asia/Shanghai
    password: root
    username: 520520
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.100.100
    port: 6379
#    password: 