server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: health_service_provider

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health?serverTimezone=Asia/Shanghai
    username: root
    password: 520520
    type: com.alibaba.druid.pool.DruidDataSource




mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.offcn.pojo